kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: workflows.argoproj.io
spec:
  group: argoproj.io
  names:
    plural: workflows
    singular: workflow
    shortNames:
      - wf
    kind: Workflow
    listKind: WorkflowList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - metadata
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              x-kubernetes-map-type: atomic
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              x-kubernetes-map-type: atomic
      subresources: {}
      additionalPrinterColumns:
        - name: Status
          type: string
          description: Status of the workflow
          jsonPath: .status.phase
        - name: Age
          type: date
          format: date-time
          description: When the workflow was started
          jsonPath: .status.startedAt
  conversion:
    strategy: None