kind: ServiceAccount
apiVersion: v1
metadata:
  name: ds-pipeline-workflow-controller-dspa
  labels:
    app: ds-pipeline-workflow-controller-dspa
    component: data-science-pipelines
    dspa: dspa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ds-pipeline-workflow-controller-role-dspa
  labels:
    app: ds-pipeline-workflow-controller-dspa
    component: data-science-pipelines
    dspa: dspa
rules:
  - verbs:
      - create
      - get
      - update
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - create
      - update
      - delete
      - get
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
      - persistentvolumeclaims/finalizers
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - create
    apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflows/finalizers
      - workflowtasksets
      - workflowtasksets/finalizers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - workflowtemplates
      - workflowtemplates/finalizers
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - list
      - watch
      - deletecollection
    apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
    apiGroups:
      - argoproj.io
    resources:
      - cronworkflows
      - cronworkflows/finalizers
  - verbs:
      - create
      - patch
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - create
      - get
      - delete
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ds-pipeline-workflow-controller-rolebinding-dspa
  labels:
    app: ds-pipeline-workflow-controller-dspa
    component: data-science-pipelines
    dspa: dspa
subjects:
  - kind: ServiceAccount
    name: ds-pipeline-workflow-controller-dspa
    namespace: rhoai-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ds-pipeline-workflow-controller-role-dspa
