apiVersion: tenantoperator.stakater.com/v1beta3
kind: Tenant
metadata:
  name: org1
spec:
  accessControl:
    editors:
      groups:
        - org1
    owners:
      users:
        - admin@org1
  namespaces:
    metadata:
      common: {}
      sandbox: {}
    onDeletePurgeNamespaces: true
    sandboxes:
      enabled: true
      private: true
    withTenantPrefix:
      - dev
      - staging
  quota: small