kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: offline-scoring-pvc
  namespace: redhat-ods-applications
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
