kind: Secret
apiVersion: v1
metadata:
  name: offline-scoring-pipeline-secret
  namespace: redhat-ods-applications
stringData:
  S3_ACCESS_KEY: "minio"
  S3_DATA_BUCKET_NAME: "data"
  S3_ENDPOINT_URL: "http://minio-service.minio.svc.cluster.local:9000"
  S3_MODEL_BUCKET_NAME: "models"
  S3_PREDICTION_BUCKET_NAME: "predictions"
  S3_SECRET_KEY: "minio123"
  MODEL_FILE_NAME: "tiny-yolov3-11.onnx"
type: Opaque
