apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-puller-workbench
  namespace: rhods-notebooks
  labels:
    k8s-app: image-puller-workbench
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      name: image-puller-workbench
  template:
    metadata:
      labels:
        name: image-puller-workbench
    spec:
      containers:
      - name: od-workbench
        image: quay.io/mmurakam/workbenches:object-detection-v1.0.5
        command: ["tail"]
        args: ["-f", "/dev/null"]
        resources:
          limits:
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 10Mi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-puller-ovms
  namespace: rhods-notebooks
  labels:
    k8s-app: image-puller-ovms
spec:
  selector:
    matchLabels:
      name: image-puller-ovms
  template:
    metadata:
      labels:
        name: image-puller-ovms
    spec:
      containers:
        - name: oauth-proxy
          image: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4bef31eb993feb6f1096b51b4876c65a6fb1f4401fee97fa4f4542b6b7c9bc46
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: ovms
          image: quay.io/opendatahub/openvino_model_server@sha256:20dbfbaf53d1afbd47c612d953984238cb0e207972ed544a5ea662c2404f276d
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: ovms-adapter
          image: registry.redhat.io/rhoai/odh-modelmesh-runtime-adapter-rhel8@sha256:5762982131a5381e582a8952a3ba336b68a1e46257f552a087da6d5a900b8bdf
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: mm
          image: registry.redhat.io/rhoai/odh-modelmesh-rhel8@sha256:b20c29b1a81e8200a81aab2361af2863889eaa3ea68f4fb19335b97949276a1b
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-puller-pipelines
  namespace: rhods-notebooks
  labels:
    k8s-app: image-puller-pipelines
spec:
  selector:
    matchLabels:
      name: image-puller-pipelines
  template:
    metadata:
      labels:
        name: image-puller-pipelines
    spec:
      containers:
        - name: mariadb
          image: registry.redhat.io/rhel8/mariadb-103@sha256:3d30992e60774f887c4e7959c81b0c41b0d82d042250b3b56f05ab67fd4cdee1
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: ds-pipeline-scheduledworkflow-pipelines-definition
          image: registry.redhat.io/rhoai/odh-ml-pipelines-scheduledworkflow-rhel8@sha256:3edce9aaa66f349c2291a161686349e0068017c7ad084146f41878f27a6eae74
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: ds-pipeline-pipelines-definition
          image: registry.redhat.io/rhoai/odh-ml-pipelines-api-server-rhel8@sha256:07954372e0e4dff0109d8d2551d059832ad87fb1fe8fbb8a54fa1c0f7878dbc1
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: oauth-proxy
          image: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:ab112105ac37352a2a4916a39d6736f5db6ab4c29bad4467de8d613e80e9bb33
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: ds-pipeline-persistenceagent-pipelines-definition
          image: registry.redhat.io/rhoai/odh-ml-pipelines-persistenceagent-rhel8@sha256:6fdf2b754aea6732ae0757e099ec69fac1cb32e633342a160546ee5b99604af7
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: object-detection-runtime
          image: quay.io/mmurakam/runtimes:object-detection-v1.1.0
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-puller-app
  namespace: rhods-notebooks
  labels:
    k8s-app: image-puller-app
spec:
  selector:
    matchLabels:
      name: image-puller-app
  template:
    metadata:
      labels:
        name: image-puller-app
    spec:
      containers:
        - name: frontend
          image: quay.io/agroom/object-detection-app
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: backend
          image: quay.io/mmurakam/object-detection-rest:v0.1.0
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi