kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-repository
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
kind: Secret
apiVersion: v1
metadata:
  name: quay-push-secret
data:
  .dockerconfigjson: REPLACE_ME
type: kubernetes.io/dockerconfigjson
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: workbench-ci
  namespace: ci
spec:
  params:
    - default: 'https://github.com/mamurak/os-mlops.git'
      description: git url to clone
      name: git-source-url
      type: string
    - default: main
      description: 'git tag to checkout'
      name: tag
      type: string
    - default: fraud-detection
      description: container source folder
      name: source-folder
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-source-url)
        - name: revision
          value: tags/$(params.tag)
        - name: sslVerify
          value: 'false'
        - name: noProxy
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: app-source
    - name: build-and-push-workbench-image
      params:
        - name: IMAGE
          value: 'quay.io/mmurakam/workbenches:$(params.tag)'
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel8/buildah@sha256:aac6629389db17e99894c5bee0da01d4c8065d11d8c6f6e1602f9484290baa70'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: container-images/$(params.source-folder)/Containerfile-workbench
        - name: CONTEXT
          value: container-images/$(params.source-folder)
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: app-source
        - name: dockerconfig
          workspace: dockersecret
    - name: build-and-push-runtime-image
      params:
        - name: IMAGE
          value: 'quay.io/mmurakam/runtimes:$(params.tag)'
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel8/buildah@sha256:aac6629389db17e99894c5bee0da01d4c8065d11d8c6f6e1602f9484290baa70'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: container-images/$(params.source-folder)/Containerfile-runtime
        - name: CONTEXT
          value: container-images/$(params.source-folder)
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: app-source
        - name: dockerconfig
          workspace: dockersecret
  workspaces:
    - name: app-source
    - name: dockersecret
