kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dashboard-permissions
  namespace: {{ .Values.app.namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/project-sharing: 'true'
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Values.app.user }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
