apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-puller-workbench
  namespace: rhods-notebooks
  labels:
    k8s-app: image-puller
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      name: image-puller
  template:
    metadata:
      labels:
        name: image-puller
    spec:
      containers:
      - name: oauth-proxy
        image: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4f8d66597feeb32bb18699326029f9a71a5aca4a57679d636b876377c2e95695
        command: ["tail"]
        args: ["-f", "/dev/null"]
        resources:
          limits:
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 10Mi
      - name: anythingllm
        image: quay.io/rh-aiservices-bu/anythingllm-workbench:1.7.4-1
        command: ["tail"]
        args: ["-f", "/dev/null"]
        resources:
          limits:
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 10Mi
      - name: ilab
        image: quay.io/rh-aiservices-bu/instructlab-workbench-code-server-cuda:0.21.0
        command: ["tail"]
        args: ["-f", "/dev/null"]
        resources:
          limits:
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 10Mi