kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: project-request
  namespace: openshift-config
objects:
  - kind: ResourceQuota
    apiVersion: v1
    metadata:
      name: resource-quota
    spec:
      hard:
        limits.cpu: '20'
        limits.memory: 20Gi
        pods: '40'
        requests.cpu: '13'
        requests.memory: 42Gi
        requests.nvidia.com/gpu: '1'
  - kind: Secret
    apiVersion: v1
    metadata:
      name: aws-connection-pipelines
      labels:
        opendatahub.io/dashboard: 'true'
        opendatahub.io/managed: 'true'
      annotations:
        opendatahub.io/connection-type: s3
        openshift.io/display-name: pipelines
    stringData:
      AWS_ACCESS_KEY_ID: REPLACE_ME
      AWS_DEFAULT_REGION: REPLACE_ME
      AWS_S3_BUCKET: REPLACE_ME
      AWS_S3_ENDPOINT: REPLACE_ME
      AWS_SECRET_ACCESS_KEY: REPLACE_ME
    type: Opaque
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: team-collaborate-rb
      labels:
        opendatahub.io/dashboard: 'true'
        opendatahub.io/project-sharing: 'true'
    subjects:
      - kind: Group
        apiGroup: rbac.authorization.k8s.io
        name: poc-participants
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: edit
  - apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
    kind: DataSciencePipelinesApplication
    metadata:
      name: dspa
    spec:
      apiServer:
        caBundleFileMountPath: ''
        stripEOF: true
        dbConfigConMaxLifetimeSec: 120
        applyTektonCustomResource: true
        caBundleFileName: ''
        deploy: true
        artifactSignedURLExpirySeconds: 60
        enableSamplePipeline: false
        autoUpdatePipelineDefaultVersion: true
        archiveLogs: false
        terminateStatus: Cancelled
        enableOauth: true
        trackArtifacts: true
        collectMetrics: true
        injectDefaultScript: true
      database:
        disableHealthCheck: false
        mariaDB:
          deploy: true
          pipelineDBName: mlpipeline
          pvcSize: 10Gi
          username: mlpipeline
      dspVersion: v2
      objectStorage:
        disableHealthCheck: false
        enableExternalRoute: false
        externalStorage:
          basePath: ''
          bucket: poc-dp-bucket-2
          host: s3.eu-central-1.amazonaws.com
          port: ''
          region: eu-central-1
          s3CredentialsSecret:
            accessKey: AWS_ACCESS_KEY_ID
            secretKey: AWS_SECRET_ACCESS_KEY
            secretName: aws-connection-pipelines
          scheme: https
      persistenceAgent:
        deploy: true
        numWorkers: 2
      podToPodTLS: true
      scheduledWorkflow:
        cronScheduleTimezone: UTC
        deploy: true
  - apiVersion: project.openshift.io/v1
    kind: Project
    metadata:
      annotations:
        openshift.io/description: '${PROJECT_DESCRIPTION}'
        openshift.io/display-name: '${PROJECT_DISPLAYNAME}'
        openshift.io/requester: '${PROJECT_REQUESTING_USER}'
      name: '${PROJECT_NAME}'
    spec: {}
    status: {}
parameters:
  - name: PROJECT_NAME
  - name: PROJECT_DISPLAYNAME
  - name: PROJECT_DESCRIPTION
  - name: PROJECT_REQUESTING_USER
