---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.component_id}}-build
  namespace: janus-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: ${{values.destination}}
    targetRevision: HEAD
    path: ./helm/ds-project
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.namespace}}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy      
  ignoreDifferences:
  - group: "*"
    kind: Notebook
    jqPathExpressions:
    - .spec.template.spec.containers[].resources
    - .spec.template.spec.containers[].image
    - .spec.template.spec.containers[].volumeMounts
    - .spec.template.spec.containers[].image
    - .spec.template.spec.containers[].env
    - .spec.template.spec.volumes
    - .metadata.annotations
    - .metadata.generation