apiVersion: v1
data:
  database-password: VXI4dXlFS1V3WWs1RTdncA==
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  labels:
    template: redis-persistent-template
    template.openshift.io/template-instance-owner: b2fb4875-bb9e-48b8-a56b-a478c7a325d8
  name: redis
type: Opaque
