kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Face recognition Elyra"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling computer vision use cases, in particular face recognition.
  name: face-recognition-elyra
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.1.0"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/face-recognition-notebook:face-recognition-notebook-v1.1.0
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"opencv","version":"4.6.0.66"},{"name":"face-recognition","version":"1.3.0"},{"name":"elyra","version":"3.14.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Code Server CUDA Data Science"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with VS Code application.
  name: code-server-cuda-data-science
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:cuda-code-server-ubi9-py39_2023b_latest
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"code-server","version":"4.9.0"},{"name":"cuda","version":"11.8.0"},{"name":"cudnn","version":"8.6.0"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Spark CUDA"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with PySpark.
  name: spark-cuda
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:cuda-jupyter-spark-ubi9-py39_2023a_20230101
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"pyspark","version":"3.3.1"},{"name":"hadoop","version":"3.3.4"},{"name":"cuda","version":"11.8.0"},{"name":"cudnn","version":"8.6.0"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "OptaPy"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with OptaPy.
  name: optapy
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:jupyter-optapy-ubi9-py39_2023a_20230101
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"optapy","version":"8.31.1b0"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "RStudio CUDA Data Science"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image RStudio application.
  name: rstudio-cuda-data-science
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:cuda-rstudio-c9s-py39_2023b_latest
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"rstudio","version":"2022.07.2-576"},{"name":"cuda","version":"11.8.0"},{"name":"cudnn","version":"8.6.0"}]
        opendatahub.io/notebook-software: '[{"name":"R","version":"4.2.2"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Monai"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with Monai.
  name: monai
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:jupyter-monai-c9s-py39_2023a_20230101
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"monai","version":"1.1.0"},{"name":"opencv","version":"4.7.0"},{"name":"torch","version":"1.13.1"},{"name":"elyra","version":"3.14.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Elyra"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with Elyra.
  name: elyra
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "0.4.0"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/elyra-notebook:elyra-notebook-v0.4.0
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"elyra","version":"3.14.1"},{"name":"scikit-learn","version":"1.2.0"},{"name":"boto3","version":"1.24.59"},{"name":"lightgbm","version":"3.3.5"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Object detection Elyra"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling computer vision use cases, in particular object detection.
  name: object-detection-elyra
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.0.2"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/object-detection-notebook:object-detection-notebook-v1.0.2
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"onnxruntime","version":"1.14.1"},{"name":"Pillow","version":"9.3.0"},{"name":"elyra","version":"3.14.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Trino Elyra"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling data integration through Trino and Starburst.
  name: trino-elyra
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "0.1.0"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/trino-notebook:trino-notebook-v0.1.0
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"trino","version":"0.323.0"},{"name":"scikit-learn","version":"0.24.2"},{"name":"elyra","version":"3.14.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'