kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Face recognition"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling computer vision use cases, in particular face recognition.
  name: face-recognition
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.0.3"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/workbenches:face-recognition-v1.0.3
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"opencv","version":"4.6.0.66"},{"name":"face-recognition","version":"1.3.0"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: ''
    opendatahub.io/notebook-image-name: HF Codeflare
    opendatahub.io/notebook-image-url: 'quay.io/mmurakam/workbenches:hf-codeflare-v0.3.0'
  name: hf-codeflare
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: v0.3.0
      annotations:
        opendatahub.io/notebook-python-dependencies: '[{"name":"Codeflare","version":"0.12.0"}]'
        opendatahub.io/notebook-software: '[{"name":"CUDA","version":"11.8"},{"name":"Python","version":"v3.9"},{"name":"PyTorch","version":"1.13"}]'
        openshift.io/imported-from: 'quay.io/mmurakam/workbenches:hf-codeflare-v0.3.0'
      from:
        kind: DockerImage
        name: 'quay.io/mmurakam/workbenches:hf-codeflare-v0.3.0'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: ''
    opendatahub.io/notebook-image-name: Timeseries
    opendatahub.io/notebook-image-url: 'quay.io/mmurakam/workbenches:timeseries-v0.2.0'
  name: custom-timeseries
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: v0.2.0
      annotations:
        opendatahub.io/notebook-python-dependencies: '[{"name":"boto3","version":"v1.28.85"}]'
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.9"}]'
        openshift.io/imported-from: 'quay.io/mmurakam/workbenches:timeseries-v0.2.0'
      from:
        kind: DockerImage
        name: 'quay.io/mmurakam/workbenches:timeseries-v0.2.0'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: ''
    opendatahub.io/notebook-image-name: Caikit
    opendatahub.io/notebook-image-url: 'quay.io/mmurakam/workbenches:caikit-v0.1.0'
  name: custom-caikit
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: caikit-v0.1.0
      annotations:
        opendatahub.io/notebook-python-dependencies: '[]'
        opendatahub.io/notebook-software: '[]'
        openshift.io/imported-from: 'quay.io/mmurakam/workbenches:caikit-v0.1.0'
      from:
        kind: DockerImage
        name: 'quay.io/mmurakam/workbenches:caikit-v0.1.0'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: ''
    opendatahub.io/notebook-image-name: VS Code mit KFP SDK
    opendatahub.io/notebook-image-url: 'quay.io/mmurakam/workbenches:vscode-kfp-v0.2.1'
  name: custom-vs-code-mit-kfp-sdk
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: vscode-kfp-v0.2.1
      annotations:
        opendatahub.io/notebook-python-dependencies: '[]'
        opendatahub.io/notebook-software: '[]'
        openshift.io/imported-from: 'quay.io/mmurakam/workbenches:vscode-kfp-v0.2.1'
      from:
        kind: DockerImage
        name: 'quay.io/mmurakam/workbenches:vscode-kfp-v0.2.1'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Spark"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with PySpark.
  name: spark
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.0.1"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/workbenches:spark-v1.0.1
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"pyspark","version":"3.3.1"},{"name":"hadoop","version":"3.3.4"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "OptaPy"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with OptaPy.
  name: optapy
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:jupyter-optapy-ubi9-py39_2023a_20230101
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"optapy","version":"8.31.1b0"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "RStudio CUDA Data Science"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image RStudio application.
  name: rstudio-cuda-data-science
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:cuda-rstudio-c9s-py39_2023b_latest
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"rstudio","version":"2022.07.2-576"},{"name":"cuda","version":"11.8.0"},{"name":"cudnn","version":"8.6.0"}]
        opendatahub.io/notebook-software: '[{"name":"R","version":"4.2.2"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Monai"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with Monai.
  name: monai
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:jupyter-monai-c9s-py39_2023a_20230101
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"monai","version":"1.1.0"},{"name":"opencv","version":"4.7.0"},{"name":"torch","version":"1.13.1"},{"name":"elyra","version":"3.14.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Object detection"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling computer vision use cases, in particular object detection.
  name: object-detection
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.0.5"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/workbenches:object-detection-v1.0.5
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"opencv","version":"4.8.0.74"},{"name":"ultralytics","version":"8.0.130"},{"name":"onnxruntime","version":"1.15.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Trino"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling data integration through Trino and Starburst.
  name: trino
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.0.0"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/workbenches:trino-v1.0.0
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"trino","version":"0.323.0"},{"name":"scikit-learn","version":"0.24.2"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Fraud detection notebook"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image for running the fraud detection demo.
  name: fraud-detection
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2.0.1"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/workbenches:fraud-detection-v2.0.1
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"tensorflow","version":"2.15.1"},{"name":"kfp","version":"2.5.0"},{"name":"scikit-learn","version":"1.4.2"},{"name":"trino","version":"0.323.0"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Langchain notebook"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with the Langchain stack.
  name: langchain
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023c"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:cuda-jupyter-langchain-c9s-py311_2023c_latest
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"langchain","version":"0.0.281"},{"name":"torch","version":"2.0.1"},{"name":"codeflare-sdk","version":"0.7.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Langflow notebook"
    opendatahub.io/notebook-image-desc: >-
      Workbench image with the Langflow IDE.
  name: langflow
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023c"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:cuda-langflow-langflow-c9s-py39_2023c_latest
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"langflow","version":"0.4.18"},{"name":"langchain","version":"0.0.256"},{"name":"torch","version":"2.0.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: JupyterLab based workbench for the sentence transformer use case
    opendatahub.io/notebook-image-name: Sentence transformer workbench
    opendatahub.io/notebook-image-url: 'quay.io/mmurakam/workbenches:sentence-transformer-v0.3.1'
  name: transformers
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: v0.3.1
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"PyTorch","version":"1.8","visible":true},{"name":"CUDA","version":"11.4","visible":true},{"name":"nltk","version":"3.8.1","visible":true},{"name":"transformers","version":"4.35.2","visible":true}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9","visible":true}]'
        openshift.io/imported-from: 'quay.io/mmurakam/workbenches:sentence-transformer-v0.3.1'
      from:
        kind: DockerImage
        name: 'quay.io/mmurakam/workbenches:sentence-transformer-v0.3.1'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: JupyterLab based workbench with InstructLab
    opendatahub.io/notebook-image-name: InstructLab Jupyter workbench
    opendatahub.io/notebook-image-url: 'quay.io/rh-aiservices-bu/instructlab-workbench-jupyter-cuda:0.1'
  name: instructlab-jupyter
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: v0.1
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"PyTorch","version":"1.8","visible":true},{"name":"CUDA","version":"11.4","visible":true}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9","visible":true}]'
        openshift.io/imported-from: 'quay.io/rh-aiservices-bu/instructlab-workbench-jupyter-cuda:0.1'
      from:
        kind: DockerImage
        name: 'quay.io/rh-aiservices-bu/instructlab-workbench-jupyter-cuda:0.1'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: VS Code based workbench with InstructLab
    opendatahub.io/notebook-image-name: InstructLab VS Code workbench
    opendatahub.io/notebook-image-url: 'quay.io/rh-aiservices-bu/instructlab-workbench-code-server-cuda:0.1'
  name: instructlab-vscode
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: v0.1
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"PyTorch","version":"1.8","visible":true},{"name":"CUDA","version":"11.4","visible":true}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9","visible":true}]'
        openshift.io/imported-from: 'quay.io/rh-aiservices-bu/instructlab-workbench-code-server-cuda:0.1'
      from:
        kind: DockerImage
        name: 'quay.io/rh-aiservices-bu/instructlab-workbench-code-server-cuda:0.1'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source