kind: Secret
apiVersion: v1
metadata:
  name: fraud-detection-offline-scoring-pipeline-secret
stringData:
  TRINO_USERNAME: "trino"
  TRINO_PASSWORD: "trino"
  TRINO_HOSTNAME: "trino-service"
  TRINO_PORT: "8080"
type: Opaque
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fraud-detection-offline-scoring-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
